version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - qt

conda:
  environment: .readthedocs_env.yml

