language: c

os:
  - linux
  - osx

sudo: false

notifications:
  email: false

env:
  global:
    - SETUP_XVFB=True
    - CONDA_CHANNELS="astrofrog/label/dev"
    - CONDA_DEPENDENCIES="astropy qtpy traitlets ipywidgets>=7.0 ipyevents widgetsnbextension pyqt pytest requests nomkl matplotlib"
    - PIP_DEPENDENCIES="sphinx-automodapi numpydoc sphinx_rtd_theme"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install .

script:
  - py.test pywwt
  - cd docs ; make html
