resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: WorldWideTelescope
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    xvfb: true
    coverage: codecov
    libraries:
      apt:
        - libxkbcommon-x11-0
        - libgl1-mesa-dev

    envs:

    - linux: codestyle
      libraries: {}
      coverage: 'false'

    - linux: py36-test
    - linux: py37-test

    - windows: py36-test
    - windows: py37-test

    # - macos: py36-test
    # - macos: py37-test

    - linux: py36-docs
    - windows: py37-docs
    - macos: py37-docs
